# https://taskfile.dev

version: '3'

vars:
  BIN: './bin'
  CLI_NAME: 'rel'
  SERVER_NAME: 'rel-server'
  SERVER_PORT: '8080'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  # Build tasks
  build:cli:
    desc: Build CLI binary
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/rel ./cmd/cli/main.go

  build:server:
    desc: Build server binary
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/rel-server ./cmd/server/main.go

  # Run tasks
  run:cli:
    desc: Run CLI
    cmds:
      - go run cmd/cli/main.go {{.CLI_ARGS}}

  run:server:
    desc: Run server
    cmds:
      - task build:server
      - go run ./cmd/server/main.go

  # Test tasks
  test:parser:
    desc: Run Parser tests
    cmds:
      - go test ./internal/parser/... -cover ./.coverage/parser.out
      - go tool cover -html ./.coverage/parser.out -o ./.coverage/parser.html